### PR TITLE
Updated list_contents.sh file

### PR DESCRIPTION
**Pull request by Bhu11154**
Users can now input the Device id when the list_contents.sh script is run. This will add the deviceId to the name of the new txt file that is being created.

### CODE REVIEW

**Review by JackMostow — APPROVED** [review]
If the output of ls -R -s is very long, is there any risk that "out" will take excessive space?

out=$(ls -R -s /sdcard/Download)

#command to create a new text file with given fileName as the name and redirecting the contents of $out into a new file
echo "$out" > /sdcard/RoboTutor/"$FILES_fileName"

If so, would this problem be solved by merging the two lines into one as follows?

echo "$(ls -R -s /sdcard/Download)" > /sdcard/RoboTutor/"$FILES_fileName"

That is, are echo and > smart enough to pipeline the output into > rather than wait to generate the entire ls before starting to write it into the file?

Otherwise, nice, simple, solution, with the added flexibility to include details such as user name, location, and device nickname.
Manual input takes time but doesn't matter if this script isn't run very often.
Manual input is susceptible to typos but that's an acceptable risk and shouldn't break anything.

**Comment by Bhu11154** [comment]
echo "$(ls -R -s /sdcard/Download)" > /sdcard/RoboTutor/"$FILES_fileName"

**Comment by Bhu11154** [comment]
I think the command = echo "$(ls -R -s /sdcard/Download)" > /sdcard/RoboTutor/"$FILES_fileName" 

will first execute "$(ls -R -s /sdcard/Download)", consuming O(N) stack space, since the listing of directories is carried out completely first, and then it's pipelined into the new txt file. 

Although removing the temporary variable $out (which again consumes O(N) space) can bring our total space from O(N) + O(N) to just O(N). But this wouldn’t significantly impact our memory usage as we will be dealing with the memory in the order of a few KBs.

**Comment by JackMostow** [comment]
I agree it's not an issue if only a few KB.  Not sure how > interacts with long  or large computation.   Thanks! - Jack

**Pull request merged**
